version: "3"

services: 
  app:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=ADMIN
      - KEYCLOAK_PASSWORD=ADMIN
      #- KEYCLOAK_IMPORT=/tmp/tests-realm-export.json
      - DB_VENDOR=h2
    ports:
      - 8080:8080