version: "3"

services: 
  app:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=ADMIN
      - KEYCLOAK_PASSWORD=ADMIN
   #   - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled          
      - DB_VENDOR=h2
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    command: 
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    ports:
      - 8080:8080